function love.conf(t)
    t.version = "11.3"
    t.console = false                           -- Attach a console (boolean, Windows only) 
    t.window.title = "Rumor Routing Simulator"  -- The window title (string)
    t.window.width = 400                        -- The window width (number)
    t.window.height = 300                        -- The window height (number)
    t.window.borderless = false                 -- Remove all border visuals from the window (boolean)
    t.window.resizable = false                  -- Let the window be user-resizable (boolean)
    t.window.vsync = true                       -- Enable vertical sync (boolean)
    t.window.fsaa = 0                           -- The number of samples to use with multi-sampled antialiasing (number)
    t.window.display = 1                        -- Index of the monitor to show the window in (number)
    t.window.highdpi = false                    -- Enable high-dpi mode for the window on a Retina display (boolean)
    t.window.srgb = true                       -- Enable sRGB gamma correction when drawing to the screen (boolean)
    t.modules.event = true                      -- Enable the event module (boolean)
    t.modules.graphics = true                   -- Enable the graphics module (boolean)
    t.modules.math = true                       -- Enable the math module (boolean)
    t.modules.mouse = true                      -- Enable the mouse module (boolean)
    t.modules.sound = true                      -- Enable the sound module (boolean)
    t.modules.system = true                     -- Enable the system module (boolean)
    t.modules.timer = true                      -- Enable the timer module (boolean)
    t.modules.window = true                     -- Enable the window module (boolean)
    t.modules.thread = true                     -- Enable the thread module (boolean)
end